pub mod app;
pub use app::MainWindow;
pub mod ipc;
pub mod stremio_player;
pub mod stremio_server;
pub mod stremio_wevbiew;
pub use ipc::RPCResponse;
pub mod named_pipe;
pub mod splash;
pub mod systray;
pub mod window_helper;
pub mod window_settings;
pub use named_pipe::{PipeClient, PipeServer};
pub mod constants;
pub mod updater;
